# Generated by Django 5.2.7 on 2025-11-02 18:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("hire_date", models.DateField()),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("uop", "Umowa o pracę"),
                            ("zlecenie", "Umowa zlecenie"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=120)),
                ("medical_check_valid_until", models.DateField(blank=True, null=True)),
                ("bhp_training_valid_until", models.DateField(blank=True, null=True)),
                ("id_card_valid_until", models.DateField(blank=True, null=True)),
                (
                    "contractor_document_valid_until",
                    models.DateField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("uop", "Umowa o pracę"),
                            ("zlecenie", "Umowa zlecenie"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "monthly_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Wymagane dla umów o pracę.",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Wymagane dla umów zlecenie.",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "expected_hours_per_month",
                    models.PositiveIntegerField(
                        default=160,
                        help_text="Liczba godzin kontrolowanych dla umowy o pracę.",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
            },
        ),
        migrations.CreateModel(
            name="LeaveRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("vacation", "Urlop wypoczynkowy"),
                            ("sick", "Zwolnienie lekarskie"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PayrollRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="Pierwszy dzień miesiąca rozliczeniowego"
                    ),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrolls",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-month", "employee__last_name"],
                "unique_together": {("employee", "month")},
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("medical", "Badania okresowe"),
                            ("bhp", "Szkolenie BHP"),
                            ("document", "Wygasający dokument"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("due_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "reminder_type"],
                "unique_together": {("employee", "reminder_type", "due_date")},
            },
        ),
        migrations.CreateModel(
            name="WorkHourEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField()),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_hours",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-work_date"],
                "unique_together": {("employee", "work_date")},
            },
        ),
    ]
