# Generated by Django 5.2.4 on 2026-01-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_latitude_company_longitude_company_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceevent',
            name='correction_reason',
            field=models.CharField(blank=True, choices=[('gps_error', 'GPS Error'), ('no_phone', 'No Phone'), ('remote_work', 'Remote Work'), ('forgot', 'Forgot'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='is_correction',
            field=models.BooleanField(default=False, help_text='Czy to jest korekta manualna'),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending_approval', 'Pending Approval'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
