# Generated by Django 5.2.7 on 2025-10-31 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('raw_payload', models.JSONField(default=list)),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('date_from', models.DateField(db_index=True)),
                ('date_to', models.DateField(db_index=True)),
                ('schedule_generated', models.BooleanField(default=False)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('override', 'Override'), ('multiplier', 'Multiplier')], default='override', max_length=16)),
                ('value', models.FloatField(help_text='If override: target demand (int). If multiplier: multiply incoming demand.')),
                ('needs_experienced_default', models.BooleanField(default=False)),
                ('min_demand', models.PositiveIntegerField(blank=True, null=True)),
                ('max_demand', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=128)),
                ('employee_name', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('experienced', models.BooleanField(default=False)),
                ('hours_min', models.PositiveIntegerField(default=0)),
                ('hours_max', models.PositiveIntegerField(default=1000000000)),
                ('available_slots', models.JSONField(default=list)),
                ('assigned_shift', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['employee_id', 'date'],
                'unique_together': {('employee_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DayDemandIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('day_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_indexes', to='schedule.demand')),
            ],
            options={
                'ordering': ['-date', 'location', '-id'],
                'indexes': [models.Index(fields=['date', 'location'], name='schedule_da_date_e1c33b_idx'), models.Index(fields=['day_hash'], name='schedule_da_day_has_5d6bd4_idx')],
                'unique_together': {('date', 'location', 'day_hash')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_uid', models.CharField(db_index=True, max_length=512, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('location', models.CharField(max_length=255)),
                ('start', models.CharField(max_length=5)),
                ('end', models.CharField(max_length=5)),
                ('demand_count', models.PositiveIntegerField(default=1)),
                ('needs_experienced', models.BooleanField(default=False)),
                ('assigned_employees', models.JSONField(default=list)),
                ('missing_minutes', models.PositiveIntegerField(default=0)),
                ('user_edited', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='schedule.demand')),
            ],
            options={
                'ordering': ['date', 'location', 'start', 'end'],
                'unique_together': {('demand', 'date', 'location', 'start', 'end')},
            },
        ),
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('location', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_days', to='schedule.eventrule')),
            ],
            options={
                'ordering': ['-date', 'location'],
                'indexes': [models.Index(fields=['date', 'location'], name='schedule_sp_date_fa07f5_idx')],
                'unique_together': {('date', 'location', 'rule')},
            },
        ),
    ]
