# Generated by Django 5.2.7 on 2025-11-01 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("schedule", "0002_defaultdemand"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="defaultdemand",
            options={"ordering": ["location", "weekday"]},
        ),
        migrations.RemoveIndex(
            model_name="daydemandindex",
            name="schedule_da_date_e1c33b_idx",
        ),
        migrations.RemoveIndex(
            model_name="daydemandindex",
            name="schedule_da_day_has_5d6bd4_idx",
        ),
        migrations.AlterUniqueTogether(
            name="daydemandindex",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="daydemandindex",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day_indexes",
                to="accounts.company",
            ),
        ),
        migrations.AddField(
            model_name="defaultdemand",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_demands",
                to="accounts.company",
            ),
        ),
        migrations.AddField(
            model_name="defaultdemand",
            name="weekday",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="0=poniedziałek ... 6=niedziela"
            ),
        ),
        migrations.AddField(
            model_name="demand",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demands",
                to="accounts.company",
            ),
        ),
        migrations.AlterField(
            model_name="defaultdemand",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="daydemandindex",
            unique_together={("company", "date", "location", "day_hash")},
        ),
        migrations.AlterUniqueTogether(
            name="defaultdemand",
            unique_together={("company", "location", "weekday")},
        ),
        migrations.AddIndex(
            model_name="daydemandindex",
            index=models.Index(
                fields=["company", "date", "location"],
                name="schedule_da_company_06876d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="daydemandindex",
            index=models.Index(
                fields=["company", "day_hash"], name="schedule_da_company_442138_idx"
            ),
        ),
    ]
