# Generated by Django 5.2.7 on 2025-11-01 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_position"),
        ("schedule", "0002_defaultdemand"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="defaultdemand",
            options={"ordering": ["location", "weekday"]},
        ),
        migrations.AddField(
            model_name="defaultdemand",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_demands",
                to="accounts.company",
            ),
        ),
        migrations.AddField(
            model_name="defaultdemand",
            name="weekday",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="defaultdemand",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="defaultdemand",
            unique_together={("company", "location", "weekday")},
        ),
        migrations.CreateModel(
            name="CompanyLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_locations",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
    ]
