# Generated by Django 5.2.7 on 2025-10-31 23:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_adopt_existing_availability_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['employee_id', 'date']},
        ),
        migrations.AddField(
            model_name='availability',
            name='assigned_shift',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='available_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='availability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(db_index=True, default=-2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='employee_id',
            field=models.CharField(db_index=True, default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='availability',
            name='experienced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availability',
            name='hours_max',
            field=models.PositiveIntegerField(default=1000000000),
        ),
        migrations.AddField(
            model_name='availability',
            name='hours_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='availability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('employee_id', 'date')},
        ),
        migrations.AlterModelTable(
            name='availability',
            table=None,
        ),
        migrations.CreateModel(
            name='DayDemandIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('day_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_indexes', to='schedule.demand')),
            ],
            options={
                'ordering': ['-date', 'location', '-id'],
                'indexes': [models.Index(fields=['date', 'location'], name='schedule_da_date_e1c33b_idx'), models.Index(fields=['day_hash'], name='schedule_da_day_has_5d6bd4_idx')],
                'unique_together': {('date', 'location', 'day_hash')},
            },
        ),
    ]
